server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://dlj:159786@localhost:8001/eureka/,http://dlj:159786@localhost:8002/eureka/,http://dlj:159786@localhost:8003/eureka/ # Eureka 服务的地址，在启动的时候需要将自身的信息注册到 Eureka 中去
  instance:
    instance-id: gateway-instance
    prefer-ip-address: true # 采用IP注册
spring:
  application:
    name: gateway-application
  cloud:
    gateway:
      routes:
        - id: consumer-application
          uri: lb://consumer-application #消费者模块的应用名
          predicates:
            - Path=/**
        - id: provider-application
          uri: lb://provider-application #生产者模块的应用名
          predicates:
            - Path=/**
