server:
  port: 8899
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/ # Eureka 服务的地址，在启动的时候需要将自身的信息注册到 Eureka 中去
  instance:
    instance-id: provider
    prefer-ip-address: true # 采用IP注册
spring:
  application:
    name: provider

