spring:
  application:
    name: eureka-server-cluster
  security:
    user:
      name: dlj
      password: 159786
  profiles:
    active: master #指定适用哪个配置进行启动
eureka:
  client:
    fetch-registry: false  # 是否允许 Eureka Client 从 Eureka Server上获取服务的注册信息 （默认是 true ：允许） # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    register-with-eureka: false # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己


---
# eureka master配置
server:
  port: 8001 # http://localhost:8001/  访问Eureka的web控制台
spring:
  application:
    name: eureka-server-master
  security:
    user:
      name: dlj
      password: 159786
  profiles: master
#eureka集群的 master
eureka:
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60000毫秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
    peer-node-read-timeout-ms: 1000
  client:
    fetch-registry: false  # 是否允许 Eureka Client 从 Eureka Server上获取服务的注册信息 （默认是 true ：允许） # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    register-with-eureka: false # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    service-url:
      defaultZone: http://dlj:159786@localhost:8002/eureka,http://dlj:159786@localhost:8003/eureka
    initial-instance-info-replication-interval-seconds: 1 #客户端信息上报到服务的周期，默认40s
    registry-fetch-interval-seconds: 1 #客户端拉取服务器配置信息的周期，默认30s,Eureka Client 上缓存的服务注册信息，定期更新的时间间隔，默认30秒：


#logging:
#  config: spring-logback-191.xml #日志配置文件

---
# eureka salve-one配置
server:
  port: 8002 # http://localhost:8001/  访问Eureka的web控制台
spring:
  application:
    name: eureka-server-salve-one
  security:
    user:
      name: dlj
      password: 159786
  profiles: salve-one
#eureka集群的 master
eureka:
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
    peer-node-read-timeout-ms: 1000
  client:
    fetch-registry: false  # 是否允许 Eureka Client 从 Eureka Server上获取服务的注册信息 （默认是 true ：允许） # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    register-with-eureka: false # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    service-url:
      defaultZone: http://dlj:159786@localhost:8001/eureka,http://dlj:159786@localhost:8003/eureka
    initial-instance-info-replication-interval-seconds: 1 #客户端信息上报到服务的周期，默认40s
    registry-fetch-interval-seconds: 1 #客户端拉取服务器配置信息的周期，默认30s
#    registry-fetch-interval-seconds: 30 # Eureka Client 上缓存的服务注册信息，定期更新的时间间隔，默认30秒：
#  instance:
#    instance-id: ybk-eureka1

#logging:
#  config: spring-logback-191.xml #日志配置文件

---
# eureka salve-two配置
server:
  port: 8003 # http://localhost:8001/  访问Eureka的web控制台
spring:
  application:
    name: eureka-server-slave-two
  security:
    user:
      name: dlj
      password: 159786
  profiles: slave-two
#eureka集群的 master
eureka:
  server:
    eviction-interval-timer-in-ms: 1000 #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
    peer-node-read-timeout-ms: 1000
  client:
    fetch-registry: false  # 是否允许 Eureka Client 从 Eureka Server上获取服务的注册信息 （默认是 true ：允许） # 由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
    register-with-eureka: false # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    service-url:
      defaultZone: http://dlj:159786@localhost:8001/eureka,http://dlj:159786@localhost:8002/eureka
    initial-instance-info-replication-interval-seconds: 1 #客户端信息上报到服务的周期，默认40s
    registry-fetch-interval-seconds: 1 #客户端拉取服务器配置信息的周期，默认30s
#    registry-fetch-interval-seconds: 30 # Eureka Client 上缓存的服务注册信息，定期更新的时间间隔，默认30秒：
#  instance:
#    instance-id: ybk-eureka1

#logging:
#  config: spring-logback-191.xml #日志配置文件